name: Dispatch Workflow
on:
  repository_dispatch:
    types: [airtable-trigger]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a script
        run: |
          echo "This workflow was triggered by Airtable via webhook!"

      - name: Configure git with your user
        run: |
          git config user.name "willyhunt"
          git config user.email "benjamin.lebotland@gmail.com"
  
      - name: Update Data File
        run: |
          echo 'null' > data.json
          git add data.json
          git commit -m "Update data file" || echo "No changes to commit"
          git push
        env:
          # This uses the PAT you stored in GitHub Secrets
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
