name: Dispatch Workflow
on:
  repository_dispatch:
    types: [airtable-trigger]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a script
        run: |
          echo "This workflow was triggered by Airtable via webhook!"
          
      - name: Update Data File
        env:
          MY_PAT: ${{ secrets.MY_PAT }} # Use the secret name you chose
        run: |
          echo 'null' > data.json
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data.json
          git commit -m "Update data file"
          # Use the PAT for authentication in the git push command
          git -c http.extraHeader="AUTHORIZATION: basic $(echo -n x-access-token:${MY_PAT} | base64)" push origin master
