name: Dispatch Workflow
on:
  repository_dispatch:
    types: [airtable-trigger]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false 

      - name: Configure git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Save payload to file
        run: |
          echo '${{ toJSON(github.event.client_payload) }}' > ./data.json
        shell: bash
      
      - name: Commit and Push Payload File
        run: |
          git add data.json
          git commit -m "Update data from webhook" || echo "No changes to commit"
          git push https://${{ secrets.MY_GITHUB_PAT }}@github.com/${GITHUB_REPOSITORY}.git HEAD:${GITHUB_REF#refs/heads/}

